services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    # Uncomment any lines below to activate that Twig extension
    #Twig\Extensions\ArrayExtension: null
    #Twig\Extensions\DateExtension: null
    Twig\Extensions\IntlExtension: null   # needed for the 'localizeddate' filter
    #Twig\Extensions\TextExtension: null
