language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=29

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - composer install
  - ./bin/phpunit install

script:
  - ./bin/phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates
  # this checks that the XLIFF translations contain no syntax errors
  - ./bin/console lint:xliff translations
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/console security:check
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
