services:
    # Required for fixtures
    slugger:
      class: AppBundle\Utils\Slugger

    # These are the Twig extensions that create new filters and functions for
    # using them in the templates
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        autowire:  true
        arguments:
            # the first argument is autowired
            1: %app_locales%
        tags:
            - { name: twig.extension }

    app.twig.intl_extension:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.redirect_to_preferred_locale_listener:
        class:     AppBundle\EventListener\RedirectToPreferredLocaleListener
        autowire:  true
        arguments:
            1: %app_locales%
            2: %locale%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Uncomment the following lines to define a service for the Post Doctrine repository.
    # It's not mandatory to create these services, but if you use repositories a lot,
    # these services simplify your code:
    #
    # app.post_repository:
    #     class:     Doctrine\ORM\EntityRepository
    #     factory:   ['@doctrine.orm.entity_manager', getRepository]
    #     arguments: [AppBundle\Entity\Post]
    #
    # // traditional code inside a controller
    # $entityManager = $this->getDoctrine()->getManager();
    # $posts = $entityManager->getRepository('AppBundle:Post')->findAll();
    #
    # // same code using repository services
    # $posts = $this->get('app.post_repository')->findAll();
